"""1.3 Separability and low rank: PSNR-against-r for disk, LoG, motion-45deg
and random kernels at k=21, on the top-left 512x512 crop of base_2048.png,
measured against exact convolution (conv2d_fft). Also saves the singular
value spectra (linear, not log, to show decay rate/energy concentration)
for the discussion of why disk needs few terms and motion-45deg needs all.
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from starter import kernel_bank, conv2d_fft, conv2d_lowrank, psnr

ROOT = Path(__file__).resolve().parents[2]
IMG_OUT = ROOT / "Report" / "Images"
IMG_OUT.mkdir(parents=True, exist_ok=True)

K = 21
full = np.asarray(Image.open(ROOT / "images/p1/base_2048.png")).astype(float)
crop = full[:512, :512]

bank = kernel_bank(K)
kernels_of_interest = ["disk", "log", "motion_45deg", "random"]

results = {}
spectra = {}
for name in kernels_of_interest:
    kernel = bank[name]
    ref = conv2d_fft(crop, kernel)
    s = np.linalg.svd(kernel, compute_uv=False)
    spectra[name] = s
    psnrs = []
    for r in range(1, K + 1):
        approx = conv2d_lowrank(crop, kernel, r)
        psnrs.append(psnr(approx, ref, peak=np.abs(ref).max()))
    results[name] = psnrs
    print(f"{name:14s} PSNR(r=1)={psnrs[0]:7.2f}  PSNR(r=3)={psnrs[2]:7.2f}  "
          f"PSNR(r=10)={psnrs[9]:7.2f}  PSNR(r={K})={psnrs[-1]:7.2f}")

# --- PSNR vs r plot ---------------------------------------------------------
fig, ax = plt.subplots(figsize=(7, 5))
markers = {"disk": "o", "log": "s", "motion_45deg": "^", "random": "d"}
for name in kernels_of_interest:
    ax.plot(range(1, K + 1), results[name], marker=markers[name], label=name, markersize=4)
ax.set_xlabel("$r$ (number of separable terms)")
ax.set_ylabel("PSNR (dB) vs. exact convolution")
ax.set_title(f"PSNR against $r$, $k={K}$, $512\\times512$ crop")
ax.legend()
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(IMG_OUT / "p1_1_3_psnr_vs_r.png", dpi=150)
plt.close(fig)

# --- Singular value spectra (linear scale, normalised) for the discussion --
fig, ax = plt.subplots(figsize=(7, 5))
for name in kernels_of_interest:
    s = spectra[name]
    ax.plot(range(1, K + 1), s / s.max(), marker=markers[name], label=name, markersize=4)
ax.set_xlabel("index $i$")
ax.set_ylabel("$\\sigma_i / \\sigma_{max}$")
ax.set_title(f"Normalised singular value spectra, $k={K}$")
ax.legend()
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(IMG_OUT / "p1_1_3_spectra_linear.png", dpi=150)
plt.close(fig)

# --- energy concentration table (cumulative sigma_i^2 / total) -------------
print("\nCumulative energy fraction (sum sigma_i^2 up to r) / (sum sigma_i^2 total):")
tex_path = ROOT / "Report" / "tables_1_3_energy.tex"
with open(tex_path, "w") as f:
    f.write("% Auto-generated by run_1_3_lowrank.py -- do not edit by hand\n")
    f.write("\\begin{tabular}{lcccc}\n\\toprule\n")
    f.write("Kernel & rank & energy at $r{=}1$ & energy at $r{=}3$ & energy at $r{=}10$ \\\\\n\\midrule\n")
    for name in kernels_of_interest:
        s = spectra[name]
        energy = np.cumsum(s**2) / np.sum(s**2)
        rank = int(np.sum(s > (max(s.shape) if hasattr(s, "shape") else K) * s.max() * np.finfo(float).eps))
        tex_name = name.replace("_", "\\_")
        f.write(f"\\texttt{{{tex_name}}} & {rank} & {energy[0]*100:.2f}\\% & "
                f"{energy[2]*100:.2f}\\% & {energy[9]*100:.2f}\\% \\\\\n")
        print(f"{name:14s} r=1: {energy[0]*100:6.2f}%  r=3: {energy[2]*100:6.2f}%  r=10: {energy[9]*100:6.2f}%")
    f.write("\\bottomrule\n\\end{tabular}\n")
print(f"\nSaved plots to {IMG_OUT}, energy table to {tex_path}")
