"""1.2 Kernel rank: numeric rank + normalised singular-value spectrum for
every kernel in the supplied bank at k=15. Saves a rank table (as text/CSV)
and a spectrum plot into Report/Images/.
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from starter import kernel_bank, numeric_rank

ROOT = Path(__file__).resolve().parents[2]
IMG_OUT = ROOT / "Report" / "Images"
IMG_OUT.mkdir(parents=True, exist_ok=True)

K = 15
bank = kernel_bank(K)

rows = []
spectra = {}
for name, kernel in bank.items():
    rank, s, tol = numeric_rank(kernel)
    s_norm = s / s.max()  # normalised singular value spectrum
    spectra[name] = s_norm
    rows.append((name, rank, s.max(), tol, s_norm[rank] if rank < len(s_norm) else 0.0))

# --- text table -----------------------------------------------------------
print(f"{'kernel':16s} {'rank':>5s} {'sigma_max':>12s} {'tol':>12s} {'sigma[rank]/max':>16s}")
for name, rank, smax, tol, s_next in rows:
    print(f"{name:16s} {rank:5d} {smax:12.4e} {tol:12.4e} {s_next:16.4e}")

# --- LaTeX table snippet ----------------------------------------------------
tex_path = IMG_OUT.parent / "tables_1_2_rank.tex"
with open(tex_path, "w") as f:
    f.write("% Auto-generated by run_1_2_rank.py -- do not edit by hand\n")
    f.write("\\begin{tabular}{lccc}\n\\toprule\n")
    f.write("Kernel & Numerical rank & $\\sigma_{\\max}$ & threshold $\\tau$ \\\\\n\\midrule\n")
    for name, rank, smax, tol, s_next in rows:
        tex_name = name.replace("_", "\\_")
        f.write(f"\\texttt{{{tex_name}}} & {rank} & {smax:.3e} & {tol:.3e} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")
print(f"\nSaved LaTeX table to {tex_path}")

# --- spectrum plot (log scale, one panel per kernel) -----------------------
names = list(bank.keys())
fig, axes = plt.subplots(3, 3, figsize=(13, 11))
for ax, name in zip(axes.ravel(), names):
    s_norm = spectra[name]
    rank = [r for n, r, *_ in rows if n == name][0]
    ax.semilogy(np.arange(1, len(s_norm) + 1), np.clip(s_norm, 1e-18, None), "o-", markersize=3)
    ax.axvline(rank + 0.5, color="red", linestyle="--", linewidth=1,
               label=f"rank={rank}")
    ax.set_title(name)
    ax.set_xlabel("index $i$")
    ax.set_ylabel("$\\sigma_i / \\sigma_{max}$")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
fig.suptitle(f"Normalised singular value spectra, k={K}")
fig.tight_layout()
fig.savefig(IMG_OUT / "p1_1_2_singular_spectra.png", dpi=150)
plt.close(fig)
print(f"Saved spectrum plot to {IMG_OUT / 'p1_1_2_singular_spectra.png'}")
