"""4.4 Automatic correction: apply auto_correct to ev0..ev4 (no per-image
parameters), report pairwise W1 distances before/after, and output luma
std/1st-99th percentile ranges (to catch a degenerate constant-output
"solution"). Includes the ev3/ev4 failure case discussion data.
"""
import sys
from pathlib import Path
from itertools import combinations

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from starter import auto_correct, hist, wasserstein1

ROOT = Path(__file__).resolve().parents[2]
IMG_OUT = ROOT / "Report" / "Images"
IMG_OUT.mkdir(parents=True, exist_ok=True)


def luma(rgb):
    rgb = rgb.astype(np.float64)
    return np.round(0.299 * rgb[..., 0] + 0.587 * rgb[..., 1] + 0.114 * rgb[..., 2]).astype(np.uint8)


originals = [np.asarray(Image.open(ROOT / f"images/p4/exposure/ev{i}.png")) for i in range(5)]
corrected = [auto_correct(im) for im in originals]

Y_before = [luma(im) for im in originals]
Y_after = [luma(im) for im in corrected]

h_before = [hist(y) for y in Y_before]
h_after = [hist(y) for y in Y_after]

pairs = list(combinations(range(5), 2))
w1_before = [wasserstein1(h_before[i], h_before[j]) for i, j in pairs]
w1_after = [wasserstein1(h_after[i], h_after[j]) for i, j in pairs]

print("Pairwise W1 distances (10 pairs):")
for (i, j), wb, wa in zip(pairs, w1_before, w1_after):
    print(f"  ev{i}-ev{j}: before={wb:8.3f}  after={wa:8.3f}")
print(f"\nmean W1 before={np.mean(w1_before):.3f}  after={np.mean(w1_after):.3f}")
print(f"max  W1 before={np.max(w1_before):.3f}  after={np.max(w1_after):.3f}")

print("\nOutput luma statistics (checking against degenerate constant output):")
for i in range(5):
    y = Y_after[i]
    p1, p99 = np.percentile(y, [1, 99])
    print(f"  ev{i}: std={y.std():.2f}  p1-p99=[{p1:.0f},{p99:.0f}]  range={p99-p1:.0f}")

fig, axes = plt.subplots(2, 5, figsize=(20, 8.5))
for i in range(5):
    axes[0, i].imshow(originals[i])
    axes[0, i].set_title(f"ev{i} (original)")
    axes[0, i].set_xticks([]); axes[0, i].set_yticks([])
    axes[1, i].imshow(corrected[i])
    std_ = Y_after[i].std()
    axes[1, i].set_title(f"ev{i} (corrected), $\\sigma$={std_:.1f}")
    axes[1, i].set_xticks([]); axes[1, i].set_yticks([])
fig.suptitle("4.4 Automatic exposure correction (parameter-free per-image percentile stretch)")
fig.tight_layout()
fig.savefig(IMG_OUT / "p4_4_4_exposure_correction.png", dpi=150)
plt.close(fig)

# W1 table
tex_path = ROOT / "Report" / "tables_4_4_w1.tex"
with open(tex_path, "w") as f:
    f.write("% Auto-generated by run_4_4_auto_correct.py -- do not edit by hand\n")
    f.write("\\begin{tabular}{lcc}\n\\toprule\n")
    f.write("Pair & W1 before & W1 after \\\\\n\\midrule\n")
    for (i, j), wb, wa in zip(pairs, w1_before, w1_after):
        f.write(f"ev{i}--ev{j} & {wb:.3f} & {wa:.3f} \\\\\n")
    f.write("\\midrule\n")
    f.write(f"Mean & {np.mean(w1_before):.3f} & {np.mean(w1_after):.3f} \\\\\n")
    f.write(f"Max & {np.max(w1_before):.3f} & {np.max(w1_after):.3f} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

stats_tex_path = ROOT / "Report" / "tables_4_4_stats.tex"
with open(stats_tex_path, "w") as f:
    f.write("% Auto-generated by run_4_4_auto_correct.py -- do not edit by hand\n")
    f.write("\\begin{tabular}{lccc}\n\\toprule\n")
    f.write("Image & Output luma std & 1st pct & 99th pct \\\\\n\\midrule\n")
    for i in range(5):
        y = Y_after[i]
        p1, p99 = np.percentile(y, [1, 99])
        f.write(f"ev{i} & {y.std():.2f} & {p1:.0f} & {p99:.0f} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

print(f"\nSaved exposure correction figure and W1/stats tables to {IMG_OUT.parent}")
